### ISSUE TITLE
Cuanto más simple mejor.

### ISSUE THREAD

**Issue by evolentini** [IvanSzkrabko/CESE_TSSS#3]
Era más fácil consultar el estado de un led justo después del inicio (seguro esta apagado) y en la otra prueba prender un solo led y consultar su estado. No están mal, pero cuanto más simples mejor.

https://github.com/IvanSzkrabko/CESE_TSSS/blob/a24b4e27d170c421ec6c57d24877510eac17bcbd/TP3/test/test_leds.c#L78-L89

**Comment by IvanSzkrabko** [comment]
issue corregido con el ultimo commit!
